language: csharp
solution: Blink1BuildStatus.sln
install:
- sudo apt-get install nunit-console
- nuget restore Blink1BuildStatus.sln
script:
- xbuild ./Fibonacci/Fibonacci.sln
- nunit-console ./Blink1BuildStatus.Test.Unit/bin/Debug/Blink1BuildStatus.Test.Unit.dll
